name: 'infra preview & deploy'

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.9.5

defaults:
  run:
    shell: bash
    working-directory: '10_infra/'

jobs:
  preview:
    name: 'Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
